apiVersion: v1
kind: Service
metadata:
  name: app1-server
  namespace: default
spec:
  type: NodePort
  selector:
    app: app1-server
    release: latest
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30808
