apiVersion: v1
kind: Service
metadata:
  name: app1-front
  namespace: default
spec:
  type: NodePort
  selector:
    app: app1-front
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30809
