apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-front
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-front
      release: stabel
  template:
    metadata:
      labels:
        app: app1-front
        release: stabel
        env: test
    spec:
      containers:
      - name: app1-server
        image: registry.cn-qingdao.aliyuncs.com/luozui/app1-front:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
      imagePullSecrets:
      - name: regcred
